version: '3.8'
services:
# ronomear para docker-compose.yml para executar os dockerfiles de test lembre-se de excluir container anteriores
  anvil:
    build:
      context: ./smartcontracts
      dockerfile: Dockerfile.anvil
    ports:
      - 8545:8545

  deploy:
    depends_on:
      - anvil
    build:
      context: ./smartcontracts
      dockerfile: Dockerfile.TestDeploy

  test:
    depends_on:
      - anvil
    build:
      context: ./smartcontracts
      dockerfile: Dockerfile.TestMint