FROM ghcr.io/foundry-rs/foundry

ENTRYPOINT [ "anvil", "--host", "0.0.0.0" ]

# abrir terminal onde está o arquivo dockerfile.anvil
# docker build -t foundry -f Dockerfile.anvil .
# docker run -p 8545:8545 foundry